# Generated by Django 5.1.6 on 2025-04-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
    ]
